const VERTICALLY_FROM_ABOVE = Symbol('VERTICALLY_FROM_ABOVE');
const VERTICALLY_FROM_BELOW = Symbol('VERTICALLY_FROM_BELOW');
const FROM_TOP_RIGHT = Symbol('FROM_TOP_RIGHT');
const FROM_BOTTOM_RIGHT = Symbol('FROM_BOTTOM_RIGHT');
const FROM_TOP_LEFT = Symbol('FROM_TOP_LEFT');
const FROM_BOTTOM_LEFT = Symbol('FROM_BOTTOM_LEFT');

export default {
  VERTICALLY_FROM_ABOVE,
  VERTICALLY_FROM_BELOW,
  FROM_TOP_RIGHT,
  FROM_BOTTOM_RIGHT,
  FROM_TOP_LEFT,
  FROM_BOTTOM_LEFT,
}
